#!/usr/bin/env node
// Agent release: [bump] → build app+DMG → sign + notarize → upload DMG + updater to AppCrane /data
// → verify the installer is served. The management server deploys separately (see the server repo).
//
//   npm run release            # release the current version
//   npm run release patch      # 0.8.16 → 0.8.17, then release
//   npm run release minor      # 0.8.16 → 0.9.0,  then release
//   npm run release 1.0.0      # set exact version, then release
//
// macOS signing/notarization activates automatically if APPLE_SIGNING_IDENTITY + APPLE_ID +
// APPLE_PASSWORD + APPLE_TEAM_ID are set (see docs/SIGNING.md). Otherwise the DMG is adhoc.
// AppCrane key: APPCRANE_API_KEY env, else the untracked .appcrane-key.local file.
import { readFileSync, writeFileSync, existsSync, copyFileSync, readdirSync, mkdirSync } from "node:fs";
import { execSync } from "node:child_process";
import { createHash } from "node:crypto";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SLUG = "raiseme";
const MCP = "https://crane.glick.run/api/mcp";
const BASE = "https://moorai.glick.run";

const KEY = process.env.APPCRANE_API_KEY
  || (existsSync(join(ROOT, ".appcrane-key.local")) ? readFileSync(join(ROOT, ".appcrane-key.local"), "utf8").trim() : "");
if (!KEY) { console.error("✗ No AppCrane key — set APPCRANE_API_KEY or create .appcrane-key.local"); process.exit(1); }

// Tauri updater signing key (produces the .app.tar.gz.sig the auto-updater verifies).
const SIGN_KEY_FILE = join(ROOT, ".tauri-signing-key.local");
if (existsSync(SIGN_KEY_FILE) && !process.env.TAURI_SIGNING_PRIVATE_KEY) {
  process.env.TAURI_SIGNING_PRIVATE_KEY = readFileSync(SIGN_KEY_FILE, "utf8").trim();
  process.env.TAURI_SIGNING_PRIVATE_KEY_PASSWORD = process.env.TAURI_SIGNING_PRIVATE_KEY_PASSWORD || "";
}

// Apple Developer ID signing + notarization (optional). Drop a gitignored .apple-signing.local with
// KEY=value lines (see .apple-signing.local.example); the build then signs + notarizes automatically.
// Until that file exists, builds are adhoc (Gatekeeper warns on first open).
const APPLE_ENV = join(ROOT, ".apple-signing.local");
if (existsSync(APPLE_ENV)) {
  for (const line of readFileSync(APPLE_ENV, "utf8").split("\n")) {
    const m = line.match(/^\s*(APPLE_[A-Z_]+)\s*=\s*(.*?)\s*$/);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^["']|["']$/g, "");
  }
  console.log(process.env.APPLE_SIGNING_IDENTITY ? `  Apple signing: ${process.env.APPLE_SIGNING_IDENTITY}` : "  .apple-signing.local present (no APPLE_SIGNING_IDENTITY)");
}

const log = (m) => console.log(`\n\x1b[36m▶ ${m}\x1b[0m`);
const sh = (cmd) => execSync(cmd, { cwd: ROOT, stdio: "inherit" });
const sha256 = (buf) => createHash("sha256").update(buf).digest("hex");
let _id = 1;
async function mcp(name, args) {
  const r = await fetch(MCP, { method: "POST", headers: { "X-API-Key": KEY, "Content-Type": "application/json", Accept: "application/json, text/event-stream" }, body: JSON.stringify({ jsonrpc: "2.0", id: _id++, method: "tools/call", params: { name, arguments: args } }) });
  const j = await r.json();
  if (j.error) throw new Error(`${name}: ${JSON.stringify(j.error)}`);
  const text = (j.result?.content || []).map((c) => c.text).join("\n");
  try { return JSON.parse(text); } catch { return text; }
}
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// ---- version ----
// The agent's version source of truth is package.json (the management server versions separately).
const PKG = join(ROOT, "package.json");
const cur = JSON.parse(readFileSync(PKG, "utf8")).version;
const arg = process.argv[2];
function next(kind) {
  if (!kind) return cur;
  if (/^\d+\.\d+\.\d+$/.test(kind)) return kind;
  const [a, b, c] = cur.split(".").map(Number);
  if (kind === "minor") return `${a}.${b + 1}.0`;
  if (kind === "patch") return `${a}.${b}.${c + 1}`;
  throw new Error(`bad version arg: ${kind} (use patch|minor|x.y.z)`);
}
const V = next(arg);
if (V !== cur) {
  log(`Bumping ${cur} → ${V}`);
  const j = JSON.parse(readFileSync(PKG, "utf8")); j.version = V; writeFileSync(PKG, JSON.stringify(j, null, 2) + "\n");
  const tc = join(ROOT, "src-tauri/tauri.conf.json"); writeFileSync(tc, readFileSync(tc, "utf8").replace(/"version": "[^"]+"/, `"version": "${V}"`));
  const cg = join(ROOT, "src-tauri/Cargo.toml"); writeFileSync(cg, readFileSync(cg, "utf8").replace(/^version = "[^"]+"/m, `version = "${V}"`));
}
// Stamp the build-info the About dialog reads (version + release date). Date passed in via args is
// unavailable here, so we use the wall clock at release time.
writeFileSync(join(ROOT, "src/buildinfo.js"), `// Generated by scripts/release.mjs at build time — do not edit by hand.\nexport const BUILD = { version: ${JSON.stringify(V)}, date: ${JSON.stringify(new Date().toISOString())} };\n`);
console.log(`\x1b[1mReleasing MoorAI v${V}\x1b[0m`);

// ---- 1. build ----
log("Building app + DMG");
console.log(process.env.APPLE_SIGNING_IDENTITY ? `  signing: ${process.env.APPLE_SIGNING_IDENTITY}` : "  adhoc (no APPLE_SIGNING_IDENTITY — DMG will warn until notarized)");
sh("npx tauri build --bundles app,dmg");
const dmgDir = join(ROOT, "src-tauri/target/release/bundle/dmg");
const dmgName = readdirSync(dmgDir).find((f) => f.endsWith(".dmg") && f.includes(`_${V}_`)) || readdirSync(dmgDir).find((f) => f.endsWith(".dmg"));
if (!dmgName) throw new Error("no DMG produced");
const buf = readFileSync(join(dmgDir, dmgName));
const sha = sha256(buf);
mkdirSync(join(ROOT, "dist"), { recursive: true });
copyFileSync(join(dmgDir, dmgName), join(ROOT, "dist/MoorAI.dmg"));
console.log(`  ${dmgName} — ${buf.length} bytes  sha256 ${sha.slice(0, 16)}…`);

// ---- 2. upload DMG to /data ----
log("Uploading installer to AppCrane /data (production)");
const up = await mcp("appcrane_set_data_blob", { slug: SLUG, env: "production", path: "MoorAI.dmg", encoding: "base64", content: buf.toString("base64") });
if (up.sha256 !== sha) throw new Error(`upload sha mismatch: local ${sha} vs stored ${up.sha256}`);
console.log(`  ${up.container_path} ✓ sha256 verified`);

// ---- 2b. upload updater artifact + signature (for in-app auto-update) ----
const macDir = join(ROOT, "src-tauri/target/release/bundle/macos");
const tgzName = readdirSync(macDir).find((f) => f.endsWith(".app.tar.gz"));
const sigName = readdirSync(macDir).find((f) => f.endsWith(".app.tar.gz.sig"));
if (tgzName && sigName) {
  log("Uploading updater artifact + signature");
  const tgz = readFileSync(join(macDir, tgzName));
  copyFileSync(join(macDir, tgzName), join(ROOT, "dist/MoorAI.app.tar.gz"));
  copyFileSync(join(macDir, sigName), join(ROOT, "dist/MoorAI.app.tar.gz.sig"));
  const ut = await mcp("appcrane_set_data_blob", { slug: SLUG, env: "production", path: "MoorAI.app.tar.gz", encoding: "base64", content: tgz.toString("base64") });
  if (ut.sha256 !== sha256(tgz)) throw new Error("updater artifact sha mismatch");
  await mcp("appcrane_set_data_blob", { slug: SLUG, env: "production", path: "MoorAI.app.tar.gz.sig", encoding: "utf-8", content: readFileSync(join(macDir, sigName), "utf8") });
  console.log(`  ${ut.container_path} (${ut.bytes} B) + signature ✓`);
} else {
  console.log("  ⚠ no updater artifact — check the 'updater' bundle target + TAURI_SIGNING_PRIVATE_KEY");
}

// ---- 3. verify the published installer ----
// The management server (separate repo) serves the DMG we just uploaded to /data — confirm it's live.
log("Verifying the published installer");
const dl = await fetch(`${BASE}/download/app`);
const dlsha = sha256(Buffer.from(await dl.arrayBuffer()));
console.log(`  /download/app: HTTP ${dl.status} — ${dlsha === sha ? "✓ sha matches build" : "✗ sha mismatch"}`);

if (dl.ok && dlsha === sha) console.log(`\n\x1b[32m✓ Released agent v${V} — installer live at ${BASE}/download/app\x1b[0m`);
else { console.log(`\n\x1b[31m✗ Release verification failed for v${V}\x1b[0m`); process.exit(1); }
